### ISSUE TITLE
The FZFPIPE file doesn't get deleted, after executing the selected command

### ISSUE THREAD

**Issue by asahaf** [Biont/sway-launcher-desktop#11]
Hi,

With the latest changes, the trap command doesn't get executed to clean up the tmp files.

The issue is caused by the way of executing the command: 
```
exec setsid /bin/sh -c "$command"
```

Thanks,

**Comment by Biont** [comment]
The launch command is now run in a sub-shell which appears to let the script cleanup properly. Thanks for catching this!
