### ISSUE TITLE
Env vars in .desktop files are not handled properly

### ISSUE THREAD

**Issue by Biont** [Biont/sway-launcher-desktop#2]
I will just copy/paste the report of @nstickney [here](https://gist.github.com/Biont/40ef59652acf3673520c7a03c9f22d2a#gistcomment-3060164)

PROBLEM:
Some *.desktop files include not just the command, but also environment variables, in the Exec line, i.e. "[`Exec=env GDK_BACKEND=x11 /opt/minecraft-launcher/minecraft-launcher`](https://aur.archlinux.org/packages/minecraft-launcher/#comment-711887)". This is apparently a [standard pattern](https://unix.stackexchange.com/questions/459172/set-multiple-environment-variables-in-desktop-file), but `swaymsg -t command "$command"` leads to `Error: Unknown/invalid command 'env'`. I tried changing the `Exec` line to `/usr/bin/env`, but I get a similar message: `Error: Unknown/invalid command '/usr/bin/env'`.

SOLUTION:
I changed the way the `$command` variable is formatted by removing the line break and[ replacing it with a space](https://gist.github.com/nstickney/e04f81be33d822fc12b55b2803142b79#file-sway-launcher-L156). Then, when running the command, I cut out ` env ` using [bash string substitution](https://gist.github.com/nstickney/e04f81be33d822fc12b55b2803142b79#file-sway-launcher-L166).

EDIT:
Note, I also [changed the ordering](https://gist.github.com/nstickney/e04f81be33d822fc12b55b2803142b79#file-sway-launcher-L25) of the `$DIRS` hoping to make the `~/.local` entry override the others, but I don't believe it has any effect.

----
Personal note: I believe part of the problem is that awk will see additional columns in an `Exec=` line like this: `Exec=env GDK_BACKEND=x11 /opt/minecraft-launcher/minecraft-launcher` since there is one more equals sign in there which we are using as a delimiter

**Comment by joefiorini** [comment]
@nstickney You can also fix the newline by using `printf` instead of `print` as I'm doing in #1.

**Comment by Biont** [comment]
@nstickney From what I can tell, this looks good now after the changes made by @joefiorini.
The minecraft-launcher.desktop file now produces the following command: `cd /opt/minecraft-launcher/ && env GDK_BACKEND=x11 /opt/minecraft-launcher/minecraft-launcher`

I added a test case for this specific issue and you can debug things more easily using `./sway-launcher-desktop.sh generate-command /path/to/application.desktop`

**Comment by nstickney** [comment]
@Biont the command as you wrote it actually fails for me:
```
[bash 5.0.11] $ swaymsg -t command "cd /opt/minecraft-launcher/ && env GDK_BACKEND=x11 /opt/minecraft-launcher/minecraft-launcher"
Error: Unknown/invalid command 'cd'
```
Is no one else seeing this behavior? `swaymsg -t command` doesn't seem to allow shell built-ins for me.

**Comment by nstickney** [comment]
`swaymsg exec` seems to fix it. Closing issue.

**Comment by Biont** [comment]
Great. Thanks for your input  @nstickney
