### ISSUE TITLE
Desktop file ID priority

### ISSUE THREAD

**Issue by DanielVoogsgerd** [Biont/sway-launcher-desktop#3]
Right now all desktop files are loaded and displayed. But according to the specification this should not be the case. The problem arises when you override a desktop file by placing it in a preceded `$XDG_DATA_DIR` directory. If the Desktop file ID is identical. The one that occurred first should be shown and all others should be ignored.

I encounter this problem with `firefox.desktop`. I have a desktop file in `~/.local/share/applications/` to override the native desktop entry. This because I want to give it the env var GDB_BACKEND=wayland

I'll leave the exact specifications below and I won't try to reformulate what is said there. The spec is quite clear.

Relevant spec:
 - https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s02.html

**Comment by Biont** [comment]
Good point. While I never really aimed for spec compliance when I started out, there's nothing really wrong with trying to get there going forward. Especially with low hanging fruit like this.

Should be easy enough to do.

Thank you for the hint.

**Comment by Biont** [comment]
@DanielVoogsgerd If you have some time, can you have a look at #4 and tell me if this solution works for you?

I initially tried to pull it of with bash (->iterate over the complete list of desktop files and skipping ones with a duplicate ID), but that solution came with a pretty noticeable performance penalty. Luckily, `awk` can do everything for us as long as we feed it the entire list of files (as opposed to one directory at a time). This still comes with some reduced performance, but it's much less noticeable

**Comment by DanielVoogsgerd** [comment]
Looks good to me!

**Comment by Biont** [comment]
@DanielVoogsgerd Please create a new issue when you find the time to have a look.
