### ISSUE TITLE
Run exact command when no matches

### ISSUE THREAD

**Issue by WhyNotHugo** [Biont/sway-launcher-desktop#31]
If I type `firefox --no-remote` there are no matches.

When I hit enter, nothing happens. Is it possible to, in this scenario, run the exact command I've typed?

**Comment by Biont** [comment]
This is something we've been exploring recently. There's even a pull request #28 for it, but I think it should be done in a slightly different way.

**Comment by Biont** [comment]
@WhyNotHugo Can you try the current master and report back?

**Comment by Biont** [comment]
Closing for now since I consider this feature working now.
