### ISSUE TITLE
Not floating

### ISSUE THREAD

**Issue by fuzunspm** [Biont/sway-launcher-desktop#36]
By default config, it's not floating unless i manually switch to floating

```
swaymsg -t get_tree | grep app_id
```

won't output launcher

.config

```
set $term termite
set $menu exec $term --class=launcher -e sway-launcher-desktop
bindsym $mod+d exec $menu
for_window [app_id="^launcher$"] floating enable, sticky enable, resize set 30 ppt 60 ppt, border pixel 10
```

**Comment by skrat** [comment]
Same issue

**Comment by skrat** [comment]
I was only able to get this work with `termite -t some-title` then matching on title

**Comment by Biont** [comment]
You can check what `window_properties` to match against with ` swaymsg -t get_tree | grep -C 10 launcher` (or something more fancy using `jq`). In my case, it looks like this with URxvt:

```
              "window_properties": {
                "class": "URxvt",
                "instance": "launcher",
                "title": "env",
                "transient_for": null
              }
```

Consequently, I actually have this in my config:
```for_window [class="URxvt" instance="launcher"] floating enable, border pixel 10, sticky enable```. 

See if that helps you and please report what worked for you so I can update the README

**Comment by skrat** [comment]
For termite, you can use `--name=foo` and that will result in app_id=foo

**Comment by fuzunspm** [comment]
thanks for the suggestions
