### ISSUE TITLE
Icons are missing

### ISSUE THREAD

**Issue by fuzunspm** [Biont/sway-launcher-desktop#39]
Possibly not related with SLD but my icons are missing. I'm sure rocket icon was visible before some updates but I don't know what broke it

![image](https://user-images.githubusercontent.com/12132746/112652666-b1716200-8e5e-11eb-9158-7083a4699f90.png)

**Comment by saxocellphone** [comment]
I fixed it by installing ttf-font-icons, but I'm not sure what happened in your case if it was working before.

**Comment by fuzunspm** [comment]
It doesn't display correctly even after ttf-font-icons

**Comment by Biont** [comment]
[Packaging on arch](https://aur.archlinux.org/packages/sway-launcher-desktop/) lists `ttf-nerd-fonts-symbols` as a dependency. Does that help?

**Comment by explorer422** [comment]
@Biont Installing `ttf-nerd-fonts-symbols` does solve the problem on arch. Cus I just had the same problem and solve it by installing it.

**Comment by Scafir** [comment]
Solved on fedora by installing `fontawesome-fonts` from the official repos.
