### ISSUE TITLE
Can't launch gedit

### ISSUE THREAD

**Issue by alanorth** [Biont/sway-launcher-desktop#40]
For some reason I can't launch gedit. When I run sway-launcher-desktop from the command line and capture the debug log I get:

```console
Starting launcher instance with the following providers: desktop user command
Launching command: screen-256color -e gedit
```

For comparison, here is what it looks like when I launch Firefox Nightly (from a `.desktop` file in my home directory):

```console
Starting launcher instance with the following providers: desktop user command
Launching command: /usr/bin/sway-launcher-desktop run-desktop '/home/aorth/.local/share/applications/firefox-nightly.desktop'
Searching for pattern: ^\\[Desktop Entry\\]
Generated Launch command from .desktop file: /home/aorth/Downloads/firefox/firefox
```

I'm running Arch Linux on Sway. What's going on here? Thanks!

**Comment by Biont** [comment]
Are there any errors when you launch the command yourself? And am I reading correctly that this is using an arbitrary command (as opposed to picking the binary)?

**Comment by alanorth** [comment]
I don't know what it's picking. I'm just starting sway-launcher-desktop and typing "gedit". Here's how it looks from the command line:

![2021-05-07T14:08:50,020951635+03:00-fs8](https://user-images.githubusercontent.com/191754/117441291-d0731180-af3d-11eb-9484-2c719d191fad.png)

And after sway-launcher-desktop just exits seemingly normally:

![2021-05-07T14:11:34,357984272+03:00-fs8](https://user-images.githubusercontent.com/191754/117441522-2b0c6d80-af3e-11eb-9e15-0d532f116c7e.png)

I'm on Arch Linux. They are using the upstream `org.gnome.gedit.desktop` file.

**Comment by alanorth** [comment]
Yeah gedit starts normally if I launch it manually via the command line or using "gedit" from another launcher such as wofi or yofi.

And yes, gedit starts correctly if I launch it as "Text Editor" from sway-launcher-desktop.
