### ISSUE TITLE
Some applications won't launch

### ISSUE THREAD

**Issue by GreyXor** [Biont/sway-launcher-desktop#57]
Hello,
I try to run `gnome-disks` but nothing happens, if I try `/usr/bin/gnome-disks` it works correctly.
From my terminal, both of them run correctly.

I'm using Arch Linux testing with sway-launcher-desktop-git

Do you have any idea why they don't start, how can i debug this ?
Thanks

**Comment by Biont** [comment]
Thanks for the report. You can dump to a log file using the [instructions in the README](https://github.com/Biont/sway-launcher-desktop#troubleshooting)

But I just installed the package and it seems to launch correctly (apart from an empty terminal window popping up. I thought this was fixed -.-)

**Comment by GreyXor** [comment]
debug log : 
`Starting launcher instance with the following providers: desktop user command`

**Comment by GreyXor** [comment]
@Biont Yes i tried to start it with log.

i just found that `Clocks` is working from sway-launcher-desktop.

**Comment by Biont** [comment]
What's your terminal emulator? Did you set an appropriate `TERMINAL_COMMAND` ? The default is `$TERMINAL -e`, where the `-e` flag is just an educated guess and something that many terminals support. 

So either define your `TERMINAL` environment variable somewhere (.bashrc) or start the launcher with a `TERMINAL_COMMAND`:

 `TERMINAL_COMMAND='foot -e' ./sway-launcher-desktop.sh `

**Comment by GreyXor** [comment]
Thanks,
i'm using Alacritty and i don't have any TERMINAL_COMMAND
here how i start sway launcher

In my sway conf:
```bindsym $mod+d exec alacritty --class launcher -e ~/bin/swaymsg-launcher-desktop.sh```


In : ~/bin/swaymsg-launcher-desktop.sh
```
#!/usr/bin/env bash
swaymsg exec "$(sway-launcher-desktop)"
```
<details>
  <summary>env</summary>
  ```

ALACRITTY_LOG=/tmp/Alacritty-15776.log
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/60177/bus
DISPLAY=:0
EDITOR=nvim
I3SOCK=/run/user/60177/sway-ipc.60177.2806.sock
INVOCATION_ID=5e8c497631d649c39294864b225337ed
JOURNAL_STREAM=8:26995
LANG=en_US.UTF-8
MOTD_SHOWN=pam
MOZ_ENABLE_WAYLAND=1
QT_QPA_PLATFORM=wayland
SHELL=/usr/bin/zsh
SHLVL=1
SUDO_EDITOR=nvim
SWAYSOCK=/run/user/60177/sway-ipc.60177.2806.sock
SYSTEMD_EXEC_PID=541
TERM=alacritty
VISUAL=nvim
WAYLAND_DISPLAY=wayland-1
XCURSOR_SIZE=24
XCURSOR_THEME=macOSBigSur
XDG_CURRENT_DESKTOP=sway
XDG_RUNTIME_DIR=/run/user/60177
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_ID=1
XDG_SESSION_TYPE=wayland
XDG_VTNR=1
_=/usr/bin/env
_JAVA_AWT_WM_NONREPARENTING=1
P9K_TTY=old
_P9K_TTY=/dev/pts/1
COMPLETION_WAITING_DOTS=true
ENABLE_CORRECTION=true
PMSPEC=0fiPs
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=
P9K_SSH=0

  ```
</details>

**Comment by GreyXor** [comment]
Thanks now it works by adding TERMINAL=alacritty in my .zshrc.

**Comment by Biont** [comment]
Great! As for the empty terminal window: This is another instance of the *command* name varying greatly from its *XDG desktop entry*.
The command `gnome-disks` will open a new window with the actual GUI. That's what happens if you type it into a CLI so of course it'll happen as well if we invoke a new terminal instance with it. We normally expect *command* entries to produce CLI output, so it makes sense to open up a new terminal instance. At least I see no real alternative here.

Now the clean way to launch GUI apps is via their desktop file. But this doesn't come up when you search for `gnome-disks` because it is actually called "Disks".

It's the same situation with `gedit` and it's "Text editor" desktop entry. I hope this further clears things up for you.

**Comment by GreyXor** [comment]
Yes, it's very clear

**Comment by liljenstolpe** [comment]
I am having some of the same problems.  I have tried with TERMINAL exported as well as not.  Alacritty, zsh, and the latest master of launcher.  

My sway config fragment (I added the explicit bash launch of launcher-desktop as a test - no effect): 
```
set $term alacritty
# set $menu rofi -show run
set $menu "$term --class launcher -e /bin/bash /sbin/sway-launcher-desktop"
```

The log below was included by making three runs from the shell
```
sway-launcher-desktop 3>> /tmp/launcher.log
```
The first was the command was an executable in my $PATH with an argument.  It did not work
```
# cam -p
```
The second was the same command, but with the path prepended.  It did work
```
# ~/.local/bin/cam -p
```
The third was firefox - which also worked
```
# firefox
```
My zsh path is replicated in my .bashrc
