### ISSUE TITLE
Why is the default -x and not -e?

### ISSUE THREAD

**Issue by chimak111** [Biont/sway-launcher-desktop#59]
In line 274, why is `-x` preferred?  
    fzf --ansi +s -x -d '\034' --nth ..3 --with-nth 3 \

Wouldn't  
    fzf --ansi +s -e -d '\034' --nth ..3 --with-nth 3 \
give quicker and cleaner results?

**Comment by Biont** [comment]
Hm, this really takes me back. I do recall giving this some thought. This is 100% personal preference, but I prefer being able to quickly enter `kpm` to adress something like "KDE Partition Manager" which would not be possible in exact mode. At the same time, you're free to type in exact search queries and fzf will most probably get you there in extended mode as well.

That said, I do intend to offer some way to add customization for fzf's behaviour in the future when I find the time to work on reading a config file again.

**Comment by chimak111** [comment]
Thank you responding! You presented an aspect that I didn't consider at all. I'm used to krunner, rofi, and wofi, which all use exact matches, AFAICT, and so I had to do a bit of head-scratching (solved by reading the `man` page).

Instead of working out customization options, it maybe easier to just put a note in the README.md covering this aspect.
