### ISSUE TITLE
how to open tui applications with launcher ?

### ISSUE THREAD

**Issue by nobodyatandnothing** [Biont/sway-launcher-desktop#63]

**Comment by Biont** [comment]
This should work. [Did you set a `TERMINAL_COMMAND`](https://github.com/Biont/sway-launcher-desktop#setup-a-terminal-command) in case the default is not working for your environment?

**Comment by nobodyatandnothing** [comment]
i set a TERMINAL_COMMAND and now its working. is there any way i can set the app id to be the name of the .desktop app?
