### ISSUE TITLE
Read input from pipe

### ISSUE THREAD

**Issue by RayZ0rr** [Biont/sway-launcher-desktop#64]
What would be a good way to implement reading from `STDIN` and using it with `sway-launcher-desktop` just like `dmenu` does?

I think the following two methods might work :

1) Make `sway-launcher-desktop` accept an argument similar to `list-entries` like `dmenu` or `stdin` which makes it call a function that reads from stdin
2) use a `PROVIDERS_FILE` with the script that reads from stdin and present it to `list_cmd`

I think the latter might be a better choice given the flexibility that provider files provide.

**Comment by Biont** [comment]
I like the idea and appreciate the solution. As you have found out, there is no clear way to do this directly *with* sway-launcher-desktop itself as it is mostly a consumer/wrapper of `fzf` with some added QoL features. History support -for example- does not work well with a feature like this. Until I get around to merge the purging branch #58 that means there will be zombie entries.

Anyway you found a nice workaround and can probably live with the tradeoffs involved. Great.

If you are adventurous, I would not be opposed to merging a PR that introduces an optional `stdin_cmd` for providers that allows any provider to process `STDIN` in some way (probably do some checks and then pipe to a tempfile). It's basically the same as your solution that way.

**Comment by RayZ0rr** [comment]
I think it's better to leave it here as an extra plugin as it's something that can be achieved with the existing capabilities of `sway-launcher-desktop`
