### ISSUE TITLE
[SOLVED] Desktop Entries Not Being Listed

### ISSUE THREAD

**Issue by electricjones** [Biont/sway-launcher-desktop#72]
This may not be a bug, but it consumed hours of my life, so I thought I'd post the problem and solution for others.

My installation was not showing any desktop entries. At all. And, I don't believe it was showing any user entries either.

It turns out that I had `mawk` installed and now `gawk`, which the script actually relies on. I'm not sure if `awk` will actually work, but I replaced all the calls to `awk` with `gawk` and everything worked fine from there.

The issue (I think) is that `BEGINFILE` and `ENDFILE` are *gawk specific* implementations and NOT part of the awk standard, and therefore not implemented by others.

Hope that saves others some headache :)

**Comment by Mikkolehtimaki** [comment]
Thanks! I also had mawk, not gawk. I'm only seeing commands not listed, not desktop files. Any more debugging ideas? On Debian bookworm.

**Comment by jbutcher93** [comment]
Thanks from Ubuntu 24.04 LTS

**Comment by bjorne** [comment]
Thanks from another Ubuntu 24.04 user. Perhaps this should be added to the README under Installation?

```
$ sudo apt install gawk
```

**Comment by Biont** [comment]
Thanks, everyone. I updated the README to reflect this
